var RT1 = [
	'Playa Caleta-RT1',
	'Playa Caletilla-RT1',
	'Plaza de Toros-RT1',
	'San Martín-RT1',
	'Tambuco-RT1',
	'La Suiza-RT1',
	'Puente Club de Pesca-RT1',
	'Playa Langosta-RT1',
	'Playa Mazanillo-RT1',
	'Paseo del Pescador-RT1',
	'Malecón-RT1',
	'Zócalo | Oviedo-RT1',
	'Melchor Ocampo-RT1',
	'Seguro Social-RT1',
	'Cine Río-RT1',
	'Flores Magón-RT1',
	'Michoacán-RT1',
	'Palacion Municipal-RT1',
	'Las Anclas-RT1',
	'Dr. Ignacio Chávez-RT1',
	'Encino-RT1',
	'Jacarandas-RT1',
	'Módulo de Policía "Y"-RT1',
	'Guadalupe Victoria-RT1',
	'La Cima-RT1',
	'Puente 1º de Mayo-RT1',
	'Puente Juan Aldama-RT1',
	'Puente La Tolva-RT1',
	'Ignacio Zaragiza-RT1',
	'Los Lirios-RT1',
	'Puente Niños Héroes-RT1',
	'Terminal de transferencia-RT1',
];

var RT2 = [
	'Zócalo | Oviedo-RT2',
	'Melchor Ocampo-RT2',
	'Seguro Social-RT2',
	'Cine Río-RT2',
	'Flores Magón-RT2',
	'Michoacán-RT2',
	'Palacio Municipal-RT2',
	'Las Anclas-RT2',
	'Dr. Ignacio Chávez-RT2',
	'Encino-RT2',
	'Jacarandas-RT2',
	'Terminal de Transferencia-RT2',
	'Zapata-RT2',
	'La Postal-RT2',
	'Vacacional-RT2',
	'Central de Abastos-RT2',
	'Leyes de Reforma-RT2',
	'Retorno-RT2',
	'La Venta-RT2',
	'Paso Limonero-RT2',
	'Vacacional-RT2',
];

var RT3 = [
	'Zócalo | Oviedo-RT3',
	'Melchor Ocampo-RT3',
	'Seguro Social-RT3',
	'Cine Río-RT3',
	'Flores Magón-RT3',
	'Michoacán-RT3',
	'Palacio Municipal-RT3',
	'Las Anclas-RT3',
	'Dr. Ignacio Chávez-RT3',
	'Encino-RT3',
	'Jacarandas-RT3',
	'Libertad-RT3',
	'Bod. Costa Chica-RT3',
	'17',
	'Cura-RT3',
	'Clínica-RT3',
	'El Rastro-RT3',
	'5 de Mayo-RT3',
	'La Máquina-RT3',
	'Planta Capama-RT3',
	'10',
	'Cruzero Cayaco-RT3',
	'Tecnológico-RT3',
	'Iglesia-RT3',
	'Piedra Roja-RT3',
	'Albañil-RT3',
	'4',
	'Peña Blanca-RT3',
	'Av. Paseo Europeo-RT3',
	'Sec. 100-RT3',
];

var RT4 = [
	'La Ceiba-RT4',
	'Fragata Zaragoza-RT4',
	'Fragata María-RT4',
	'Almirante C.C.-RT4',
	'Nao Victoria-RT4',
	'Almendro-RT4',
	'Palmas-RT4',
	'Deportes-RT4',
	'Delprado-RT4',
	'Torres Gemelas-RT4',
	'Playa Condesa-RT4',
	'El Morro-RT4',
	'La Diana-RT4',
	'Av. Universidad-RT4',
	'Navegante Juan Pérez-RT4',
	'Mercado de Artesanías-RT4',
	'G. de Sandoval-RT4',
	'Palacio Municipal-RT4',
	'Michoacán-RT4',
	'Flores Magón-RT4',
	'Cine Río-RT4',
	'Seguro Social-RT4',
	'Melchor Ocampo-RT4',
	'Zócalo | Oviedo-RT4',
];

var RT5 = [
	'La Ceiba-RT5',
	'Fragata Zaragoza-RT5',
	'Fragata María-RT5',
	'Almirante C.C.-RT5',
	'Nao Victoria-RT5',
	'Almendro-RT5',
	'Palmas-RT5',
	'Deportes-RT5',
	'Delprado-RT5',
	'Torres Gemelas-RT5',
	'Playa Condesa-RT5',
	'El Morro-RT5',
	'La Diana-RT5',
	'Arroyo-RT5',
	'Los Amates-RT5',
	'Terminal de Transferencia-RT5',
];

var RA1 = [
	'Palma Sola-RA1',
	'Río Atoyac-RA1',
	'Eje Vicente Guerrero-RA1',
	'Jose María Izazaga-RA1',
	'Cuauhtémoc-RA1',
	'Canal del Arroyo-RA1',
	'Icacos-RA1',
	'Julián Blanco-RA1',
	'Jesús Salgado-RA1',
	'Alta Cuauhtémoc-RA1',
	'Eduardo Neri-RA1',
	'Nicolás Bravo-RA1',
	'Ejido las Pozas-RA1',
	'Zapata-RA1',
	'Terminal de Transferencia-RA1',
];

var RA2 = [
	'Av. del Capire-RA2',
	'Circuito-RA2',
	'Av. de la Ceiba-RA2',
	'Orizaba-RA2',
	'Atlixtac-RA2',
	'Tlapehuala-RA2',
	'Nautla-RA2',
	'Vacacional-RA2',
	'La Postal-RA2',
	'Zapata-RA2',
	'Terminal de Transferencia-RA2',
];

var RA3 = [
	'Santo Tomás-RA3',
	'Ventura Escobar-RA3',
	'Zócalo-RA3',
	'Fco. I. Madero-RA3',
	'Av. del Tanque-RA3',
	'Cion. Tres Tamarindos-RA3',
	'Chico Portillo-RA3',
	'And. Bugambilias-RA3',
	'10 de Mayo-RA3',
	'La Venta-RA3',
	'Retorno-RA3',
	'Leyes de Reforma-RA3',
	'Central de Abastos-RA3',
	'Paso Limonero-RA3',
	'Vacacional-RA3',
	'La Postal-RA3',
	'Zapata -RA3',
	'Terminal de Transferencia-RA3',
];

var RA4 = [
	'Tulipanes-RA4',
	'Clavel-RA4',
	'And. Fabrica-RA4',
	'Calle 15-RA4',
	'Calle 10-RA4',
	'Olivos-RA4',
	'Vacacional-RA4',
	'La Postal-RA4',
	'Zapata-RA4',
	'Terminal de Transferencia-RA4',
];

var RA5 = [
	'Cocula-RA5',
	'Simón Bolivar-RA5',
	'Calle 14-RA5',
	'Calle 10-RA5',
	'Calle 27-RA5',
	'Calle 23-RA5',
	'Calle 17-RA5',
	'Calle 11-RA5',
	'Calle 7-RA5',
	'Calle 3-RA5',
	'Zapata-RA5',
	'Terminal de Transferencia-RA5',
];

var RA6 = [
	'Vicente Guerrero-RA6',
	'Simón Bolivar-RA6',
	'Venustiano Carranza-RA6',
	'Francisco Márquez-RA6',
	'San Patricio-RA6',
	'Acuario-RA6',
	'20 de Noviembre-RA6',
	'Av. de las Cruces-RA6',
];

var RA7 = [
	'2 de Abril-RA7',
	'Av. Cumbres-RA7',
	'Jorullo-RA7',
	'Popocatépetl -RA7',
	'Av. del Colegio-RA7',
	'Las Conchas-RA7',
	'Glorieta-RA7',
	'M. Heredia-RA7',
	'Jacarandas-RA7',
	'Bugambilias-RA7',
];

var RA8 = [
	'2 de Abril-RA8',
	'Av. Cumbres-RA8',
	'Jorullo-RA8',
	'Popocatépetl -RA8',
	'Av. del Colegio-RA8',
	'Alejandro Cervantes-RA8',
	'Dragos-RA8',
	'Los Amates-RA8',
	'Arroyo-RA8',
	'Bodega Comercial M. -RA8',
	'La Diana-RA8',
	'Av. Bella Vista-RA8',
	'Av. Universidad-RA8',
	'Y. Yáñez Pinzón-RA8',
	'Norte -RA8',
	'La Nao-RA8',
	'G. de Sandoval -RA8',
	'Las Anclas-RA8',
	'Av. Universidad-RA8',
];

var RA9 = [
	'Monte Everest-RA9',
	'Juan de Dios Bonilla-RA9',
	'Niños Héroes de Veracruz-RA9',
	'Castillo Bretón-RA9',
	'Fernando Magallanes-RA9',
	'Av. Horacio Nelson-RA9',
	'Cristobal Colón-RA9',
	'Almirante C.C.-RA9',
];

var RA10 = [
	'Condominio D-RA10',
	'Tuxpan-RA10',
	'Nautla-RA10',
	'Tampico-RA10',
	'Río Coyuca-RA10',
	'Tepic-RA10',
	'Nogales-RA10',
	'Querétaro-RA10',
	'Durango-RA10',
	'Zacatecas-RA10',
	'Tamaulipas-RA10',
	'Torreón-RA10',
	'Sonora-RA10',
	'Flores Magón-RA10',
	'Michoacán-RA10',
	'Chihuahua-RA10',
];
var RA11 = [
	'Condominio D-RA11',
	'Tuxpan-RA11',
	'Nautla-RA11',
	'Tampico-RA11',
	'Río Coyuca-RA11',
	'Bernal Díaz del Castillo-RA11',
	'Baja California-RA11',
	'Querétaro-RA11',
	'Chiapas-RA11',
	'Oaxaca-RA11',
	'Colima-RA11',
	'Jalapa-RA11',
	'Nuevo León-RA11',
	'Cda. de Vallarta-RA11',
	'Miguel Acuña-RA11',
	'Av. Sonora-RA11',
	'Coahuila-RA11',
];